apiVersion: k3d.io/v1alpha3
kind: Simple 
name: dev-lab-3m-5w
servers: 3 
agents: 5
image: rancher/k3s:v1.21.5-k3s2
registries:
  create:
    name: registry.labs
    host: "0.0.0.0"
    hostPort: "5000"
volumes:
  - volume: /tmp/volumes/k3d/:/volumes/k3d
    nodeFilters:
      - agent:*
ports:
  - port: 30000:30000
    nodeFilters:
      - agent:0
  - port: 30001:30001
    nodeFilters:
      - agent:0
  - port: 30002:30002
    nodeFilters:
      - agent:0
options:
  k3d: 
    wait: true 
    timeout: "180s" 
    disableImageVolume: false 
  kubeconfig:
    updateDefaultKubeconfig: true 
    switchCurrentContext: true 
  k3s:
    nodeLabels:
      - label: sharedvol=true
        nodeFilters:
          - agent:*